version: 0.2

env:
  variables:
    stage: "prod"
  parameter-store:
    config_json: "office-maker-client-config-prod"

phases:
  install:
    commands:
      - npm i -g elm@0.18
      - elm-package install -y
      - npm install
      - echo ${config_json} >> config.${stage}.json
  build:
    commands:
      - aws s3 sync s3://office-maker-client-artifacts/doc doc
      - sh ./build.sh ${stage}
  post_build:
    commands: |
      if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/master" ]; then
        sh ./deploy.sh ${stage} <<EOF
          yes
        EOF;
      fi;

