version: 0.2

env:
  variables:
    stage: "stg"
  parameter-store:
    config_json: "office-maker-client-config-stg"

phases:
  install:
    commands:
      - npm i -g elm@0.18
      - elm-package install -y
      - npm install
      - echo ${config_json} >> config.${stage}.json
  pre_build:
    commands:
      - aws s3 sync s3://office-maker-client-artifacts/doc doc
      - sh ./build.sh ${stage}
  build:
    commands: |
      if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/release" ]; then
        sh ./deploy.sh ${stage} <<EOF
          yes
      EOF
      fi;

